server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true


spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6397

    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
